### ISSUE TITLE
Layout TODO List

### ISSUE THREAD

**Issue by greenfrog82** [greenfrog82/LetEatGo#7]
* Main Page 
  * [ ] Menubar + 상단 디자인 + 검색 창
  * [ ] Content 영역의 맛집 리스트 출력 그리드
* Perspective Menu Page
  * [ ] Main page와 별도 Layout 구성
